name: Deploy to SIT
on:
  push:
    branches:
      - sit

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |
          iwr https://aka.ms/PowerAppsCLIInstall -OutFile pac.msi
          msiexec /i pac.msi /quiet

     
