name: Deploy to SIT
on:
  push:
    branches:
      - sit

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |
          iwr https://aka.ms/PowerAppsCLIInstall -OutFile pac.msi
          msiexec /i pac.msi /quiet

      - name: Authenticate to SIT Environment
        run: pac auth create --url https://<SIT_ENV_URL> --name SIT --username ${{ secrets.SIT_USERNAME }} --password ${{ secrets.SIT_PASSWORD }}

      - name: Import Solution to SIT
        run: pac solution import --path solutions/Solution1.zip --async
``
